# Generated by Django 4.2.7 on 2023-11-27 22:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.categoria'),
        ),
        migrations.AlterField(
            model_name='equipe',
            name='esporte',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.esporte'),
        ),
    ]
