# Generated by Django 4.2.7 on 2023-11-27 22:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_curso_categoria_alter_equipe_esporte'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='curso',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='app.curso'),
        ),
    ]
