# Generated by Django 4.2.7 on 2023-11-28 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_usuario_curso'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='senha',
            field=models.CharField(default='', max_length=61),
        ),
        migrations.AddField(
            model_name='usuario',
            name='ususario',
            field=models.CharField(default='', max_length=50),
        ),
    ]
