# Generated by Django 4.2.7 on 2023-12-10 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_usuario_senha_usuario_ususario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='ususario',
            new_name='usuario',
        ),
    ]
